[build]
builder = "dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stack"
CACHE_DRIVER = "file"
QUEUE_CONNECTION = "sync"
SESSION_DRIVER = "file"
SESSION_LIFETIME = "120"

[environments.production.deploy]
healthcheckPath = "/"
healthcheckTimeout = 300